@startuml SubjectStateMachine
left to right direction

state DRAFT
state PUBLISHED

[*] --> DRAFT: Create subject
DRAFT --> PUBLISHED: All lessons have quiz & video
PUBLISHED --> DRAFT: Unpublish
DRAFT --> [*]
PUBLISHED --> [*]

@enduml
