Enum "achievements_type_enum" {
  "EVENT_COUNT"
  "PROPERTY_CHECK"
  "STREAK"
}

Enum "auth_providers_provider_enum" {
  "local"
  "google"
  "facebook"
  "github"
  "twitter"
  "microsoft"
  "apple"
  "linkedin"
  "amazon"
  "gitlab"
  "instagram"
  "yahoo"
  "slack"
  "discord"
  "custom"
  "other"
}

Enum "coaches_verification_status_enum" {
  "PENDING"
  "APPROVED"
  "REJECTED"
}

Enum "configurations_data_type_enum" {
  "string"
  "number"
  "boolean"
  "json"
}

Enum "courses_learning_format_enum" {
  "INDIVIDUAL"
  "GROUP"
}

Enum "courses_level_enum" {
  "BEGINNER"
  "INTERMEDIATE"
  "ADVANCED"
}

Enum "credentials_type_enum" {
  "CERTIFICATE"
  "PRIZE"
  "ACHIEVEMENT"
}

Enum "enrollments_status_enum" {
  "PENDING_GROUP"
  "CONFIRMED"
  "REFUNDED"
}

Enum "learner_progresses_status_enum" {
  "IN_PROGRESS"
  "COMPLETED"
  "DROPPED_OUT"
}

Enum "learner_skill_assessments_status_enum" {
  "IN_PROGRESS"
  "COMPLETED"
}

Enum "learner_videos_status_enum" {
  "UPLOADING"
  "READY"
  "ERROR"
  "ANALYZING"
}

Enum "learners_learning_goal_enum" {
  "BEGINNER"
  "INTERMEDIATE"
  "ADVANCED"
}

Enum "learners_skill_level_enum" {
  "BEGINNER"
  "INTERMEDIATE"
  "ADVANCED"
}

Enum "notifications_status_enum" {
  "PENDING"
  "SENT"
  "DELIVERED"
  "READ"
  "FAILED"
  "CANCELED"
  "ERROR"
}

Enum "payments_status_enum" {
  "PENDING"
  "COMPLETED"
  "CANCELLED"
  "FAILED"
  "ERROR"
}

Enum "quizzes_level_enum" {
  "BEGINNER"
  "INTERMEDIATE"
  "ADVANCED"
}

Enum "request_actions_type_enum" {
  "APPROVED"
  "REJECTED"
}

Enum "requests_status_enum" {
  "PENDING"
  "APPROVED"
  "REJECTED"
}

Enum "requests_type_enum" {
  "COURSE_APPROVAL"
  "COACH_VERIFICATION"
  "CONTENT_APPROVAL"
}

Enum "schedules_day_of_week_enum" {
  "Monday"
  "Tuesday"
  "Wednesday"
  "Thursday"
  "Friday"
  "Saturday"
  "Sunday"
}

Enum "session_earnings_status_enum" {
  "PENDING"
  "CALCULATED"
  "PAID"
  "FAILED"
}

Enum "sessions_coach_payment_status_enum" {
  "PENDING"
  "COMPLETED"
  "CANCELLED"
  "FAILED"
  "ERROR"
}

Enum "sessions_status_enum" {
  "SCHEDULED"
  "COMPLETED"
  "CANCELLED"
}

Enum "skill_assessment_templates_status_enum" {
  "DRAFT"
  "ACTIVE"
  "ARCHIEVED"
}

Enum "video_conference_presence_logs_event_type_enum" {
  "USER_JOIN"
  "USER_LEAVE"
  "CHANNEL_START"
  "CHANNEL_END"
}

Enum "videos_status_enum" {
  "UPLOADING"
  "READY"
  "ERROR"
  "ANALYZING"
}

Enum "wallet_transactions_type_enum" {
  "CREDIT"
  "DEBIT"
}

Enum "withdrawal_requests_status_enum" {
  "PENDING"
  "PROCESSING"
  "COMPLETED"
  "FAILED"
}

Table "migrations" {
  "id" int4 [pk, not null, increment]
  "timestamp" int8 [not null]
  "name" varchar [not null]
}

Table "errors" {
  "id" int4 [pk, not null, increment]
  "code" varchar(255) [not null]
  "message" text [not null]
  "stack" varchar(5000)
  "url" varchar(255)
  "body" varchar(255)
  "created_at" timestamp [not null, default: `now()`]
  "resolved_at" timestamp [not null, default: `now()`]
  "isResolved" bool [not null, default: false]
  "user_id" int4
}

Table "roles" {
  "id" int4 [pk, not null, increment]
  "name" varchar(50) [unique, not null]
}

Table "auth_providers" {
  "id" int4 [pk, not null, increment]
  "provider" auth_providers_provider_enum [not null]
  "provider_id" varchar(100) [unique, not null]
  "created_at" timestamp [not null, default: `now()`]
  "user_id" int4
}

Table "notifications" {
  "id" int4 [pk, not null, increment]
  "title" varchar(50) [not null]
  "body" text [not null]
  "status" notifications_status_enum [not null, default: 'PENDING']
  "created_at" timestamp [not null, default: `now()`]
  "user_id" int4 [not null]
}

Table "credentials" {
  "id" int4 [pk, not null, increment]
  "name" varchar(255) [not null]
  "description" text
  "type" credentials_type_enum [not null]
  "public_url" text
  "issued_at" date
  "expires_at" date
  "created_at" timestamp [not null, default: `now()`]
  "updated_at" timestamp [not null, default: `now()`]
  "deleted_at" timestamp
  "coach_id" int4
}

Table "coaches" {
  "id" int4 [pk, not null, increment]
  "bio" text [not null]
  "specialties" text
  "teaching_methods" text
  "year_of_experience" int4 [not null]
  "verification_status" coaches_verification_status_enum [not null, default: 'PENDING']
  "created_at" timestamp [not null, default: `now()`]
  "updated_at" timestamp [not null, default: `now()`]
  "deleted_at" timestamp
  "user_id" int4

  Indexes {
    user_id [type: btree, name: "IDX_bd9923ac72efde2d5895e118fa"]
  }
}

Table "request_actions" {
  "id" int4 [pk, not null, increment]
  "type" request_actions_type_enum [not null]
  "comment" text
  "created_at" timestamp [not null, default: `now()`]
  "handled_by" int4
  "request_id" int4
}

Table "requests" {
  "id" int4 [pk, not null, increment]
  "description" text [not null]
  "type" requests_type_enum [not null, default: 'COURSE_APPROVAL']
  "status" requests_status_enum [not null, default: 'PENDING']
  "metadata" jsonb
  "created_at" timestamp [not null, default: `now()`]
  "updated_at" timestamp [not null, default: `now()`]
  "created_by" int4
}

Table "video_conference_presence_logs" {
  "id" int4 [pk, not null, increment]
  "channel_name" varchar(100) [not null]
  "event_type" video_conference_presence_logs_event_type_enum [not null]
  "timestamp" timestamp [not null, default: `now()`]
  "user_id" int4
}

Table "learners" {
  "id" int4 [pk, not null, increment]
  "skill_level" learners_skill_level_enum [not null, default: 'BEGINNER']
  "learning_goal" learners_learning_goal_enum [not null, default: 'BEGINNER']
  "userId" int4
}

Table "schedules" {
  "id" int4 [pk, not null, increment]
  "day_of_week" schedules_day_of_week_enum [not null]
  "start_time" time [not null]
  "end_time" time [not null]
  "course_id" int4
}

Table "notes" {
  "id" int4 [pk, not null, increment]
  "content" text [not null]
  "created_at" timestamp [not null, default: `now()`]
  "updated_at" timestamp [not null, default: `now()`]
  "created_by" int4
  "session_id" int4
  "received_by" int4
}

Table "attendances" {
  "id" int4 [pk, not null, increment]
  "created_at" timestamp [not null, default: `now()`]
  "user_id" int4
  "session_id" int4
}

Table "session_quizzes" {
  "id" int4 [pk, not null, increment]
  "created_at" timestamp [not null, default: `now()`]
  "sessionId" int4
  "quizId" int4
}

Table "quizzes" {
  "id" int4 [pk, not null, increment]
  "title" varchar(50) [not null]
  "description" text
  "level" quizzes_level_enum [not null, default: 'BEGINNER']
  "total_questions" int4 [not null]
}

Table "question_options" {
  "id" int4 [pk, not null, increment]
  "content" text [not null]
  "is_correct" bool [not null, default: false]
  "question_id" int4
}

Table "questions" {
  "id" int4 [pk, not null, increment]
  "title" varchar(100) [not null]
  "explanation" text
  "quiz_id" int4
}

Table "learner_answers" {
  "id" int4 [pk, not null, increment]
  "is_correct" bool [not null]
  "created_at" timestamp [not null, default: `now()`]
  "question_id" int4
  "quiz_attempt_id" int4
  "question_option_id" int4
}

Table "quiz_attempts" {
  "id" int4 [pk, not null, increment]
  "attempt_number" int4 [not null]
  "score" int4 [not null]
  "created_at" timestamp [not null, default: `now()`]
  "attempted_by" int4
  "session_id" int4
}

Table "wallet_transactions" {
  "id" int4 [pk, not null, increment]
  "amount" int4 [not null]
  "description" text
  "type" wallet_transactions_type_enum [not null]
  "created_at" timestamp [not null, default: `now()`]
  "wallet_id" int4
  "session_id" int4
  "withdrawal_request_id" int4
}

Table "session_earnings" {
  "id" int4 [pk, not null, increment]
  "session_price" int8 [not null]
  "coach_earning_total" int8 [not null]
  "status" session_earnings_status_enum [not null, default: 'PENDING']
  "created_at" timestamp [not null, default: `now()`]
  "paid_at" date
  "session_id" int4
}

Table "session_videos" {
  "id" int4 [pk, not null, increment]
  "created_at" timestamp [not null, default: `now()`]
  "sessionId" int4
  "videoId" int4
}

Table "videos" {
  "id" int4 [pk, not null, increment]
  "title" varchar(50) [not null]
  "description" text
  "tags" text
  "duration" int4 [not null]
  "drill_name" varchar(50)
  "drill_description" text
  "drill_practice_sets" text
  "public_url" text [not null]
  "thumbnail_url" text
  "status" videos_status_enum [not null, default: 'UPLOADING']
}

Table "skill_assessment_templates" {
  "id" int4 [pk, not null, increment]
  "name" varchar(100) [not null]
  "description" text
  "status" skill_assessment_templates_status_enum [not null, default: 'DRAFT']
  "created_at" timestamp [not null, default: `now()`]
  "updated_at" timestamp [not null, default: `now()`]
  "created_by" int4
}

Table "learner_skill_assessments" {
  "id" int4 [pk, not null, increment]
  "status" learner_skill_assessments_status_enum [not null, default: 'IN_PROGRESS']
  "created_at" timestamp [not null, default: `now()`]
  "user_id" int4
  "learner_video_id" int4
  "skill_assessment_template_id" int4
}

Table "ai_video_comparison_results" {
  "id" int4 [pk, not null, increment]
  "summary" text
  "learner_score" int4
  "keyDifferents" jsonb
  "details" jsonb
  "recommendationDrills" jsonb
  "created_at" timestamp [not null, default: `now()`]
  "learner_video_id" int4
  "video_id" int4
  "learnerSkillAssessmentId" int4

  Indexes {
    video_id [type: btree, name: "IDX_8f9dd918b2f5f9b0f701e9f3a5"]
    learner_video_id [type: btree, name: "IDX_ce6caf58efab20a6485b1e465e"]
  }
}

Table "learner_videos" {
  "id" int4 [pk, not null, increment]
  "tags" text
  "duration" int4 [not null]
  "public_url" text [not null]
  "thumbnail_url" text
  "status" learner_videos_status_enum [not null, default: 'UPLOADING']
  "created_at" timestamp [not null, default: `now()`]
  "user_id" int4
  "session_id" int4
}

Table "sessions" {
  "id" int4 [pk, not null, increment]
  "name" varchar(100)
  "description" text
  "session_number" int4 [not null]
  "schedule_date" date [not null]
  "start_time" time [not null]
  "end_time" time [not null]
  "duration_in_minutes" int4 [not null]
  "video_conference_channel_name" varchar(100)
  "video_conference_link" text
  "status" sessions_status_enum [not null, default: 'SCHEDULED']
  "created_at" timestamp [not null, default: `now()`]
  "updated_at" timestamp [not null, default: `now()`]
  "deletedAt" timestamp
  "completed_at" date
  "coach_payment_status" sessions_coach_payment_status_enum [not null, default: 'PENDING']
  "course_id" int4
}

Table "payments" {
  "id" int4 [pk, not null, increment]
  "amount" int8 [not null]
  "coach_earning_total" int8 [not null]
  "status" payments_status_enum [not null, default: 'PENDING']
  "external_transaction_id" text
  "created_at" timestamp [not null, default: `now()`]
  "enrollment_id" int4
}

Table "enrollments" {
  "id" int4 [pk, not null, increment]
  "status" enrollments_status_enum [not null, default: 'PENDING_GROUP']
  "enrolled_at" timestamp [not null, default: `now()`]
  "updated_at" timestamp [not null, default: `now()`]
  "course_id" int4
  "learner_id" int4
}

Table "feedbacks" {
  "id" int4 [pk, not null, increment]
  "comment" text [not null]
  "rating" int4 [not null]
  "created_at" timestamp [not null, default: `now()`]
  "deleted_at" timestamp
  "user_id" int4
  "course_id" int4
}

Table "learner_progresses" {
  "id" int4 [pk, not null, increment]
  "sessions_completed" int4 [not null]
  "total_sessions" int4 [not null]
  "avg_quiz_score" int4 [not null]
  "status" learner_progresses_status_enum [not null, default: 'IN_PROGRESS']
  "updated_at" timestamp [not null, default: `now()`]
  "user_id" int4
  "course_id" int4
}

Table "courses" {
  "id" int4 [pk, not null, increment]
  "name" varchar(100) [not null]
  "description" text
  "level" courses_level_enum [not null, default: 'BEGINNER']
  "learning_format" courses_learning_format_enum [not null, default: 'INDIVIDUAL']
  "min_participants" int4 [not null, default: 1]
  "max_participants" int4 [not null, default: 10]
  "price_per_participant" int8 [not null, default: '0']
  "start_date" date [not null]
  "end_date" date [not null]
  "created_at" timestamp [not null, default: `now()`]
  "updated_at" timestamp [not null, default: `now()`]
  "deleted_at" timestamp
  "created_by" int4
}

Table "learner_achievements" {
  "id" int4 [pk, not null, increment]
  "earned_at" timestamp [not null, default: `now()`]
  "achievement_id" int4
  "user_id" int4
}

Table "achievements" {
  "id" int4 [pk, not null, increment]
  "name" varchar(100) [not null]
  "description" text
  "icon_url" text
  "is_active" bool [not null, default: true]
  "created_at" timestamp [not null, default: `now()`]
  "event_name" varchar(25)
  "target_streak_length" int4
  "streak_unit" varchar(25)
  "entity_name" varchar(25)
  "property_name" varchar(25)
  "comparison_operator" varchar(25)
  "target_value" text
  "target_count" int4
  "type" achievements_type_enum [not null]
  "created_by" int4

  Indexes {
    type [type: btree, name: "IDX_6261fe3636483beee9db8fd370"]
  }
}

Table "achievement_progresses" {
  "id" int4 [pk, not null, increment]
  "current_progress" int4 [not null]
  "updated_at" timestamp [not null, default: `now()`]
  "achievement_id" int4
  "user_id" int4

  Indexes {
    user_id [type: btree, name: "IDX_5c049bcfd1bdc064529502cea6"]
    achievement_id [type: btree, name: "IDX_7bbff2ff7709c4bfe2ec171cb0"]
  }
}

Table "configurations" {
  "id" int4 [pk, not null, increment]
  "key" varchar(25) [unique, not null]
  "value" varchar(255) [not null]
  "description" text
  "data_type" configurations_data_type_enum [not null, default: 'string']
  "created_at" timestamp [not null, default: `now()`]
  "updated_at" timestamp [not null, default: `now()`]
  "created_by" int4
  "updated_by" int4
}

Table "users" {
  "id" int4 [pk, not null, increment]
  "full_name" varchar(50) [not null]
  "email" varchar(50) [unique]
  "phone_number" varchar(25)
  "password" varchar(255)
  "profile_picture" text
  "refresh_token" text
  "is_email_verified" bool [not null, default: false]
  "email_verification_token" varchar(255)
  "reset_password_token" varchar(255)
  "is_active" bool [not null, default: false]
  "created_at" timestamp [not null, default: `now()`]
  "updated_at" timestamp [not null, default: `now()`]
  "deleted_at" timestamp
  "role_id" int4

  Indexes {
    is_email_verified [type: btree, name: "IDX_1abbfecef5aefa239aca51ccc5"]
    is_active [type: btree, name: "IDX_20c7aea6112bef71528210f631"]
    role_id [type: btree, name: "IDX_a2cecd1a3531c0b041e29ba46e"]
  }
}

Table "wallets" {
  "id" int4 [pk, not null, increment]
  "current_balance" int8 [not null]
  "total_income" int8 [not null]
  "created_at" timestamp [not null, default: `now()`]
  "updated_at" timestamp [not null, default: `now()`]
  "userId" int4 [unique]
}

Table "withdrawal_requests" {
  "id" int4 [pk, not null, increment]
  "amount" int8 [not null]
  "status" withdrawal_requests_status_enum [not null, default: 'PENDING']
  "payout_details" text
  "admin_comment" text
  "requested_at" timestamp [not null, default: `now()`]
  "completed_at" date
  "wallet_id" int4
}

Ref "FK_5c049bcfd1bdc064529502cea6b":"users"."id" < "achievement_progresses"."user_id"

Ref "FK_7bbff2ff7709c4bfe2ec171cb08":"achievements"."id" < "achievement_progresses"."achievement_id"

Ref "FK_f013825ee12ed3dbe4503bd8b68":"users"."id" < "achievements"."created_by"

Ref "FK_389da34ca9a2e80edb0967bcca5":"learner_skill_assessments"."id" < "ai_video_comparison_results"."learnerSkillAssessmentId"

Ref "FK_8f9dd918b2f5f9b0f701e9f3a58":"videos"."id" < "ai_video_comparison_results"."video_id"

Ref "FK_ce6caf58efab20a6485b1e465e2":"learner_videos"."id" < "ai_video_comparison_results"."learner_video_id"

Ref "FK_aa902e05aeb5fde7c1dd4ced2b7":"users"."id" < "attendances"."user_id" [delete: cascade]

Ref "FK_ccb4752e27a2927234e1f3dc960":"sessions"."id" < "attendances"."session_id" [delete: cascade]

Ref "FK_262996fd08ab5a69e85b53d0055":"users"."id" < "auth_providers"."user_id" [delete: cascade]

Ref "FK_bd9923ac72efde2d5895e118fa8":"users"."id" < "coaches"."user_id" [delete: cascade]

Ref "FK_06000e3d345edfed86dde6d4b28":"users"."id" < "configurations"."created_by"

Ref "FK_5e0eaa5b677fd4a19ce7b213738":"users"."id" < "configurations"."updated_by"

Ref "FK_16fcd8ab8bc042688984d5b3934":"users"."id" < "courses"."created_by" [delete: set null]

Ref "FK_8cbbe3785bbd0c6af75acac1bfe":"coaches"."id" < "credentials"."coach_id" [delete: cascade]

Ref "FK_b79d0bf01779fdf9cfb6b092af3":"courses"."id" < "enrollments"."course_id" [delete: cascade]

Ref "FK_bb53c1a95eb92bf25d7c632058e":"users"."id" < "enrollments"."learner_id" [delete: cascade]

Ref "FK_9ebca22261064ed68a1c894017e":"users"."id" < "errors"."user_id"

Ref "FK_4334f6be2d7d841a9d5205a100e":"users"."id" < "feedbacks"."user_id"

Ref "FK_b46afcad144f370d8a4c55ea498":"courses"."id" < "feedbacks"."course_id"

Ref "FK_a77d3e9606c8288f6bc5a148132":"achievements"."id" < "learner_achievements"."achievement_id" [delete: cascade]

Ref "FK_df9cac0ea1f4f223ad48efdb119":"users"."id" < "learner_achievements"."user_id"

Ref "FK_57238eb2290f2081def653b4ac1":"question_options"."id" < "learner_answers"."question_option_id" [delete: cascade]

Ref "FK_a88a71b4134638af1e0b211db36":"quiz_attempts"."id" < "learner_answers"."quiz_attempt_id" [delete: cascade]

Ref "FK_b93f29c3adfa47910e5cbc741b6":"questions"."id" < "learner_answers"."question_id" [delete: cascade]

Ref "FK_47edc74266d1ccf71687a8b5d96":"users"."id" < "learner_progresses"."user_id" [delete: cascade]

Ref "FK_b21b5f43200685ef0309fc36a5e":"courses"."id" < "learner_progresses"."course_id" [delete: cascade]

Ref "FK_1d0347da71a1f23a2f175ea1c3d":"users"."id" < "learner_skill_assessments"."user_id"

Ref "FK_23e21adfb8cd11c843e42b4a7e1":"learner_videos"."id" < "learner_skill_assessments"."learner_video_id"

Ref "FK_f32b867871e50a7438f20d78fea":"skill_assessment_templates"."id" < "learner_skill_assessments"."skill_assessment_template_id"

Ref "FK_37fb5e426810144dcbbbc4ab2b2":"sessions"."id" < "learner_videos"."session_id"

Ref "FK_cf04457186a977ccc49446bec52":"users"."id" < "learner_videos"."user_id"

Ref "FK_28e1f470fea3f1c5196c2e4464f":"users"."id" < "learners"."userId" [delete: cascade]

Ref "FK_61f3e1f13a15b883ae34a9e28c9":"sessions"."id" < "notes"."session_id" [delete: cascade]

Ref "FK_b86c5f2b5de1e7a3d2a428cfb55":"users"."id" < "notes"."created_by" [delete: cascade]

Ref "FK_f7857b0d8f027e0a2eb094e381e":"users"."id" < "notes"."received_by" [delete: cascade]

Ref "FK_9a8a82462cab47c73d25f49261f":"users"."id" < "notifications"."user_id"

Ref "FK_1a390dc6ab65942f1ab577b7b65":"enrollments"."id" < "payments"."enrollment_id" [delete: cascade]

Ref "FK_f0b7aaabd3f88e700daf0fe681c":"questions"."id" < "question_options"."question_id" [delete: cascade]

Ref "FK_46b3c125e02f7242662e4ccb307":"quizzes"."id" < "questions"."quiz_id" [delete: cascade]

Ref "FK_3c151c1db4d493cee059d94aeb8":"users"."id" < "quiz_attempts"."attempted_by"

Ref "FK_d244675816bf64833d8ecd67830":"sessions"."id" < "quiz_attempts"."session_id"

Ref "FK_28fe00d6aca3eb711eae98f8cc6":"users"."id" < "request_actions"."handled_by" [delete: cascade]

Ref "FK_8c6c5b31c8d9f2571c99dd4550b":"requests"."id" < "request_actions"."request_id" [delete: cascade]

Ref "FK_2d487b151e34f5924c3d8adb5da":"users"."id" < "requests"."created_by" [delete: cascade]

Ref "FK_b1e10ac4dc72412af1c3f4d736d":"courses"."id" < "schedules"."course_id" [delete: cascade]

Ref "FK_d0660e6799fc1ee26ffd3c3c381":"sessions"."id" < "session_earnings"."session_id" [delete: cascade]

Ref "FK_3852caaaab79dc1007c2a6156c7":"quizzes"."id" < "session_quizzes"."quizId" [delete: cascade]

Ref "FK_ed58d18f1bf5f98d77ec8d3493c":"sessions"."id" < "session_quizzes"."sessionId" [delete: cascade]

Ref "FK_8c596e6f41192da2605d6abf2c5":"videos"."id" < "session_videos"."videoId" [delete: cascade]

Ref "FK_b3666bc6d714b5c52017264b14b":"sessions"."id" < "session_videos"."sessionId" [delete: cascade]

Ref "FK_b8cfc5397ec5c262e83f2bf5fbe":"courses"."id" < "sessions"."course_id" [delete: cascade]

Ref "FK_21414b56511886e8a4c060145ff":"users"."id" < "skill_assessment_templates"."created_by" [delete: cascade]

Ref "FK_a2cecd1a3531c0b041e29ba46e1":"roles"."id" < "users"."role_id"

Ref "FK_724e21ec4efa4582794e1ddc835":"users"."id" < "video_conference_presence_logs"."user_id"

Ref "FK_5c9c1f45c2ecec8d6cc8b8691e3":"sessions"."id" < "wallet_transactions"."session_id" [delete: cascade]

Ref "FK_c57d19129968160f4db28fc8b28":"wallets"."id" < "wallet_transactions"."wallet_id" [delete: cascade]

Ref "FK_fcca97f70af59b1dcd047024c3c":"withdrawal_requests"."id" < "wallet_transactions"."withdrawal_request_id" [delete: cascade]

Ref "FK_2ecdb33f23e9a6fc392025c0b97":"users"."id" < "wallets"."userId" [delete: cascade]

Ref "FK_09ba365288c710bc15432553fcd":"wallets"."id" < "withdrawal_requests"."wallet_id" [delete: cascade]
