version: '3.8'

services:
  api-gateway:
    build: .
    environment:
      - NODE_ENV=production
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USERNAME=postgres
      - DB_PASSWORD=password
      - DB_NAME=capstone_db
      - API_GATEWAY_PORT=8386
      - API_GATEWAY_HOST=0.0.0.0
    depends_on:
      - postgres
    volumes:
      - ./uploads:/usr/src/app/uploads
    ports:
      - "8386:8386"
    restart: unless-stopped

  postgres:
    image: postgres:15-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=capstone_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  postgres_data: