version: '3.9'

services:
  api-gateway:
    build:
      context: .
      dockerfile: Dockerfile.service
      args:
        SERVICE: api-gateway
    environment:
      - service_var=api-gateway
    env_file:
      - .env.production
    ports:
      - '${API_GATEWAY_PORT}:${API_GATEWAY_PORT}'
  auth-service:
    build:
      context: .
      dockerfile: Dockerfile.service
      args:
        SERVICE: auth-service
    environment:
      - service_var=auth-service
    env_file:
      - .env.production
    ports:
      - '${AUTH_SERVICE_PORT}:${AUTH_SERVICE_PORT}'
  user-service:
    build:
      context: .
      dockerfile: Dockerfile.service
      args:
        SERVICE: user-service
    environment:
      - service_var=user-service
    env_file:
      - .env.production
    ports:
      - '${USER_SERVICE_PORT}:${USER_SERVICE_PORT}'
  notification-service:
    build:
      context: .
      dockerfile: Dockerfile.service
      args:
        SERVICE: notification-service
    environment:
      - service_var=notification-service
    env_file:
      - .env.production
  mail-service:
    build:
      context: .
      dockerfile: Dockerfile.service
      args:
        SERVICE: mail-service
    environment:
      - service_var=mail-service
    env_file:
      - .env.production
  payment-service:
    build:
      context: .
      dockerfile: Dockerfile.service
      args:
        SERVICE: payment-service
    environment:
      - service_var=payment-service
    env_file:
      - .env.production
  order-service:
    build:
      context: .
      dockerfile: Dockerfile.service
      args:
        SERVICE: order-service
    environment:
      - service_var=order-service
    env_file:
      - .env.production
