@startuml Pickleball Platform - Package Diagram
title Package Diagram - Backend

left to right direction

[middleware] as middleware
[guard] as guard
[dto] as dto
[controller] as controller
[socket] as socket
[service] as service
[entity] as entity
[filter] as filter
[util] as util

middleware --> guard
guard --> dto
dto --> controller
controller --> service
socket --> service
service --> util
service --> entity
util --> filter
entity --> filter


@enduml
