export enum AuthProviderEnum {
  LOCAL = 'local',
  GOOGLE = 'google',
  FACEBOOK = 'facebook',
  GITHUB = 'github',
  TWITTER = 'twitter',
  MICROSOFT = 'microsoft',
  APPLE = 'apple',
  LINKEDIN = 'linkedin',
  AMAZON = 'amazon',
  GITLAB = 'gitlab',
  INSTAGRAM = 'instagram',
  YAHOO = 'yahoo',
  SLACK = 'slack',
  DISCORD = 'discord',
  CUSTOM = 'custom',
  OTHER = 'other',
}
