export enum PickleBallLevelEnum {
  BEGINNER_1_0 = 'BEGINNER_1_0',
  BEGINNER_1_5 = 'BEGINNER_1_5',
  BEGINNER_2_0 = 'BEGINNER_2_0',
  BEGINNER_2_5 = 'BEGINNER_2_5',
  INTERMEDIATE_3_0 = 'INTERMEDIATE_3_0',
  INTERMEDIATE_3_5 = 'INTERMEDIATE_3_5',
  ADVANCED_4_0 = 'ADVANCED_4_0',
  ADVANCED_4_5 = 'ADVANCED_4_5',
  EXPERT_5_0 = 'EXPERT_5_0',
  EXPERT_5_5 = 'EXPERT_5_5',
}

export enum PickleBallSkillEnum {
  FOREHAND = 'FOREHAND',
  BACKHAND = 'BACKHAND',
  SLICE = 'SLICE',
  SERVE = 'SERVE',
  VOLLEY = 'VOLLEY',
  SMASH = 'SMASH',
  GRIP = 'GRIP',
  DINK = 'DINK',
  LOB = 'LOB',
  SPIN = 'SPIN',
  RESET = 'RESET',
  BLOCK = 'BLOCK',
}

export enum PickleBallLearnerGoal {
  HAVE_FUN = 'HAVE_FUN',
  IMPROVE_SKILLS = 'IMPROVE_SKILLS',
  COMPETE = 'COMPETE',
}

export enum PickleBallMonthlyMatches {
  ONE_TO_TEN = 'ONE_TO_TEN',
  ELEVEN_TO_TWENTY_FIVE = 'ELEVEN_TO_TWENTY_FIVE',
  TWENTY_SIX_TO_FIFTY = 'TWENTY_SIX_TO_FIFTY',
  FIFTY_PLUS = 'FIFTY_PLUS',
}

export enum PickleBallAssessMethod {
  SELF_ASSESSMENT = 'SELF_ASSESSMENT',
  COACH_ASSESSMENT = 'COACH_ASSESSMENT',
  AI_ASSESSMENT = 'AI_ASSESSMENT',
  QUIZ_ASSESSMENT = 'QUIZ_ASSESSMENT',
}
