export enum PickleBallLevelEnum {
  BEGINNER_1_0 = 'BEGINNER_1_0',
  BEGINNER_1_5 = 'BEGINNER_1_5',
  BEGINNER_2_0 = 'BEGINNER_2_0',
  BEGINNER_2_5 = 'BEGINNER_2_5',
  INTERMEDIATE_3_0 = 'INTERMEDIATE_3_0',
  INTERMEDIATE_3_5 = 'INTERMEDIATE_3_5',
  ADVANCED_4_0 = 'ADVANCED_4_0',
  ADVANCED_4_5 = 'ADVANCED_4_5',
  EXPERT_5_0 = 'EXPERT_5_0',
  EXPERT_5_5 = 'EXPERT_5_5',
}

export enum PickleBallSkillEnum {
  FOREHAND = 'FOREHAND',
  BACKHAND = 'BACKHAND',
  SLICE = 'SLICE',
  SERVE = 'SERVE',
  VOLLEY = 'VOLLEY',
  SMASH = 'SMASH',
  GRIP = 'GRIP',
  DINK = 'DINK',
  LOB = 'LOB',
  SPIN = 'SPIN',
  RESET = 'RESET',
  BLOCK = 'BLOCK',
}
