export enum RequestType {
  COURSE_APPROVAL = 'COURSE_APPROVAL',
  COURSE_CANCELLATION = 'COURSE_CANCELLATION',
  COACH_VERIFICATION = 'COACH_VERIFICATION',
  QUIZ_APPROVAL = 'QUIZ_APPROVAL',
  COACH_VIDEO_APPROVAL = 'COACH_VIDEO_APPROVAL',
}

export enum RequestStatus {
  PENDING = 'PENDING',
  APPROVED = 'APPROVED',
  REJECTED = 'REJECTED',
}

export enum RequestActionType {
  APPROVED = 'APPROVED',
  REJECTED = 'REJECTED',
}
