export enum RequestType {
  COURSE_APPROVAL = 'COURSE-APPROVAL',
  COURSE_CANCELLATION = 'COURSE-CANCELLATION',
  COACH_VERIFICATION = 'COACH-VERIFICATION',
  COACH_UPDATE_VERIFICATION = 'COACH-UPDATE-VERIFICATION',
  COURSE_UPDATE_APPROVAL = 'COURSE-UPDATE-APPROVAL',
}

export enum RequestStatus {
  PENDING = 'PENDING',
  APPROVED = 'APPROVED',
  REJECTED = 'REJECTED',
}

export enum RequestActionType {
  APPROVED = 'APPROVED',
  REJECTED = 'REJECTED',
}
