export enum TransactionType {
  COURSE_PAYMENT = 'COURSE_PAYMENT',
  COACH_EARNING = 'COACH_EARNING',
  SYSTEM_COMMISSION = 'SYSTEM_COMMISSION',
  REFUND = 'REFUND',
  WITHDRAWAL = 'WITHDRAWAL',
  DEPOSIT = 'DEPOSIT',
}